# yamllint configuration
# https://yamllint.readthedocs.io

extends: default

rules:
  # Line length (disable - let editor handle soft-wrapping)
  line-length: disable

  # Document markers (allow files without explicit markers)
  document-start: disable

  # Truthy values (allow common boolean representations)
  truthy:
    allowed-values: ['true', 'false', 'on', 'off', 'yes', 'no']

  # Indentation (2 spaces, consistent)
  indentation:
    spaces: 2
    indent-sequences: consistent

  # Comments (require space after #)
  comments:
    require-starting-space: true
    min-spaces-from-content: 1

  # Braces (allow space inside braces for readability)
  braces:
    min-spaces-inside: 0
    max-spaces-inside: 1

  # Brackets (allow space inside brackets)
  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 1
